import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import React, { useState } from 'react';
import useFetch from '../hooks/useFetch';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const { cipheredFetch } = useFetch();

  const [value, setValue] = useState({
    signature: '',
    character: '',
  });

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const response = await cipheredFetch(
      'http://localhost:3001/placeholder',
      JSON.stringify(value)
    );

    console.log(response);
  };

  const handleChange = (event: React.FormEvent<HTMLInputElement>) => {
    setValue({
      ...value,
      [event.currentTarget.id]: event.currentTarget.value,
    });
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href='https://nextjs.org'>Next.js!</a>
        </h1>
        <br />
        <form
          onSubmit={handleSubmit}
          style={{ display: 'flex', flexDirection: 'column', gap: 16 }}
        >
          <input
            onChange={handleChange}
            type='text'
            placeholder='Signature'
            id='signature'
          />
          <input
            onChange={handleChange}
            type='text'
            placeholder='Character'
            id='character'
          />
          <button type='submit'>Submit</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
          target='_blank'
          rel='noopener noreferrer'
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
